package views;

import usuarios.UsuarioPadrao;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Miqueias
 */
public class Home extends javax.swing.JFrame {
    private UsuarioPadrao user;
    /**
     * Creates new form Home
     */
    public Home(UsuarioPadrao user) {
        this.user = user;
        initComponents();
    }
    
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonConfiguracoes = new javax.swing.JButton();
        buttonLogOut = new javax.swing.JButton();
        buttonJogo6 = new javax.swing.JButton();
        buttonJogo9 = new javax.swing.JButton();
        buttonJogo2 = new javax.swing.JButton();
        buttonJogo4 = new javax.swing.JButton();
        buttonJogo5 = new javax.swing.JButton();
        buttonJogo3 = new javax.swing.JButton();
        buttonJogo7 = new javax.swing.JButton();
        buttonJogo10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("MEUS JOGOS");

        buttonConfiguracoes.setText("Configuracoes");
        buttonConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfiguracoesActionPerformed(evt);
            }
        });

        buttonLogOut.setText("Log Out");
        buttonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogOutActionPerformed(evt);
            }
        });

        buttonJogo6.setText("Farm Heroes");
        buttonJogo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJogo6ActionPerformed(evt);
            }
        });

        buttonJogo9.setText("Dota 2");
        buttonJogo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJogo9ActionPerformed(evt);
            }
        });

        buttonJogo2.setText("GTA V");
        buttonJogo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJogo2ActionPerformed(evt);
            }
        });

        buttonJogo4.setText("LOL");
        buttonJogo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJogo4ActionPerformed(evt);
            }
        });

        buttonJogo5.setText("Clash Of Clans");
        buttonJogo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJogo5ActionPerformed(evt);
            }
        });

        buttonJogo3.setText("Shadow Of The Colossus");
        buttonJogo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJogo3ActionPerformed(evt);
            }
        });

        buttonJogo7.setText("Elder Ring");
        buttonJogo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJogo7ActionPerformed(evt);
            }
        });

        buttonJogo10.setText("Fobia");
        buttonJogo10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJogo10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonLogOut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonConfiguracoes))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonJogo5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonJogo6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonJogo7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonJogo10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonJogo9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonJogo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonJogo3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonJogo4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonConfiguracoes)
                    .addComponent(buttonLogOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonJogo4)
                    .addComponent(buttonJogo3)
                    .addComponent(buttonJogo9)
                    .addComponent(buttonJogo2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonJogo7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonJogo5)
                        .addComponent(buttonJogo10)
                        .addComponent(buttonJogo6)))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonJogo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJogo6ActionPerformed
        this.setVisible(false);
        Post posts = new Post(this.user);
        posts.setVisible(true);
    }//GEN-LAST:event_buttonJogo6ActionPerformed

    private void buttonJogo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJogo2ActionPerformed
        this.setVisible(false);
        Post posts = new Post(this.user);
        posts.setVisible(true);
    }//GEN-LAST:event_buttonJogo2ActionPerformed

    private void buttonJogo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJogo4ActionPerformed
        this.setVisible(false);
        Post posts = new Post(this.user);
        posts.setVisible(true);
    }//GEN-LAST:event_buttonJogo4ActionPerformed

    private void buttonJogo9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJogo9ActionPerformed
        this.setVisible(false);
        Post posts = new Post(this.user);
        posts.setVisible(true);
    }//GEN-LAST:event_buttonJogo9ActionPerformed

    private void buttonJogo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJogo3ActionPerformed
        this.setVisible(false);
        Post posts = new Post(this.user);
        posts.setVisible(true);
    }//GEN-LAST:event_buttonJogo3ActionPerformed

    private void buttonJogo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJogo5ActionPerformed
        this.setVisible(false);
        Post posts = new Post(this.user);
        posts.setVisible(true);
    }//GEN-LAST:event_buttonJogo5ActionPerformed

    private void buttonJogo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJogo7ActionPerformed
        this.setVisible(false);
        Post posts = new Post(this.user);
        posts.setVisible(true);
    }//GEN-LAST:event_buttonJogo7ActionPerformed

    private void buttonJogo10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJogo10ActionPerformed
        this.setVisible(false);
        Post posts = new Post(this.user);
        posts.setVisible(true);
    }//GEN-LAST:event_buttonJogo10ActionPerformed

    private void buttonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogOutActionPerformed
        this.setVisible(false);
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
    }//GEN-LAST:event_buttonLogOutActionPerformed

    private void buttonConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfiguracoesActionPerformed
        this.setVisible(false);
        Configuracoes configuracoes = new Configuracoes(this.user);
        configuracoes.setVisible(true);
    }//GEN-LAST:event_buttonConfiguracoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConfiguracoes;
    private javax.swing.JButton buttonJogo10;
    private javax.swing.JButton buttonJogo2;
    private javax.swing.JButton buttonJogo3;
    private javax.swing.JButton buttonJogo4;
    private javax.swing.JButton buttonJogo5;
    private javax.swing.JButton buttonJogo6;
    private javax.swing.JButton buttonJogo7;
    private javax.swing.JButton buttonJogo9;
    private javax.swing.JButton buttonLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
