package views;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mique
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonPerfil = new javax.swing.JButton();
        buttonHome = new javax.swing.JButton();
        buttonJogo1 = new javax.swing.JButton();
        buttonJogo2 = new javax.swing.JButton();
        buttonJogo3 = new javax.swing.JButton();
        buttonJogo4 = new javax.swing.JButton();
        buttonJogo5 = new javax.swing.JButton();
        buttonJogo6 = new javax.swing.JButton();
        buttonJogo7 = new javax.swing.JButton();
        buttonJogo8 = new javax.swing.JButton();
        buttonLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("MEUS JOGOS");

        buttonPerfil.setText("Perfil");

        buttonHome.setText("Home");
        buttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHomeActionPerformed(evt);
            }
        });

        buttonJogo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MDI\\Faculdade\\Main\\src\\main\\java\\Imagens\\Rectangle 4.png")); // NOI18N

        buttonJogo2.setIcon(new javax.swing.ImageIcon("C:\\Users\\MDI\\Faculdade\\Main\\src\\main\\java\\Imagens\\Rectangle 5.png")); // NOI18N

        buttonJogo3.setIcon(new javax.swing.ImageIcon("C:\\Users\\MDI\\Faculdade\\Main\\src\\main\\java\\Imagens\\Rectangle 6.png")); // NOI18N

        buttonJogo4.setIcon(new javax.swing.ImageIcon("C:\\Users\\MDI\\Faculdade\\Main\\src\\main\\java\\Imagens\\Rectangle 7.png")); // NOI18N

        buttonJogo5.setIcon(new javax.swing.ImageIcon("C:\\Users\\MDI\\Faculdade\\Main\\src\\main\\java\\Imagens\\Rectangle 8.png")); // NOI18N

        buttonJogo6.setIcon(new javax.swing.ImageIcon("C:\\Users\\MDI\\Faculdade\\Main\\src\\main\\java\\Imagens\\Rectangle 9.png")); // NOI18N
        buttonJogo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJogo6ActionPerformed(evt);
            }
        });

        buttonJogo7.setIcon(new javax.swing.ImageIcon("C:\\Users\\MDI\\Faculdade\\Main\\src\\main\\java\\Imagens\\Rectangle 10.png")); // NOI18N

        buttonJogo8.setIcon(new javax.swing.ImageIcon("C:\\Users\\MDI\\Faculdade\\Main\\src\\main\\java\\Imagens\\Rectangle 12.png")); // NOI18N
        buttonJogo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJogo8ActionPerformed(evt);
            }
        });

        buttonLogOut.setText("Log Out");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonLogOut)
                        .addGap(41, 41, 41)
                        .addComponent(buttonPerfil))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonJogo5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonJogo6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonJogo7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonJogo8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonJogo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonJogo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonJogo3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(20, 20, 20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonJogo4)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPerfil)
                    .addComponent(buttonHome)
                    .addComponent(buttonLogOut))
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonJogo1)
                    .addComponent(buttonJogo2)
                    .addComponent(buttonJogo4)
                    .addComponent(buttonJogo3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonJogo6)
                    .addComponent(buttonJogo7)
                    .addComponent(buttonJogo8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonJogo5))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonJogo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJogo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonJogo6ActionPerformed

    private void buttonJogo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJogo8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonJogo8ActionPerformed

    private void buttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHome;
    private javax.swing.JButton buttonJogo1;
    private javax.swing.JButton buttonJogo2;
    private javax.swing.JButton buttonJogo3;
    private javax.swing.JButton buttonJogo4;
    private javax.swing.JButton buttonJogo5;
    private javax.swing.JButton buttonJogo6;
    private javax.swing.JButton buttonJogo7;
    private javax.swing.JButton buttonJogo8;
    private javax.swing.JButton buttonLogOut;
    private javax.swing.JButton buttonPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
